server:
  port: 8081
spring:
  application:
    name: home-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/home_db
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
