server:
  port: 8083
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5435/cart_db
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
